### ISSUE TITLE
Links dont work

### ISSUE THREAD

**Issue by AdrianRang** [ramondeleonca/ignition.blue#2]
When going from home to any other page you dont get the contents and have to reload
<img width="1440" alt="Screenshot 2024-04-02 at 8 52 12 a m" src="https://github.com/ramondeleonca/ignition.blue/assets/142278016/d72198a4-50c7-4139-bbc5-19275735ca08">
I get this when i got to somewhere else

**Comment by ramondeleonca** [comment]
shut up

**Comment by ramondeleonca** [comment]
idc

**Comment by ramondeleonca** [comment]
shut up again
